GRASS_TYPE_START = 1
GRASS_TYPE_END = 5

ANIMATIVES = [
    {
        "name" : "unknown",
        "index" : 0,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "animative_type" : "g",
    },
    {
        "name" : "suntrap",
        "index" : 1,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "animative_type" : "F",
        "evolves_to" : 2,
    },
    {
        "name": "solizz",
        "index": 2,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "F",
        "evolves_to": 3,
    },
    {
        "name": "solizant",
        "index": 3,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "F",
        "evolves_to": None,
    },
    {
        "name": "cuberry",
        "index": 4,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": 5,
    },
    {
        "name": "berroar",
        "index": 5,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": 6,
    },
    {
        "name": "strawberrier",
        "index": 6,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": None,
    },
    {
        "name": "dropleet",
        "index": 7,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": 8,
    },
    {
        "name": "aquant",
        "index": 8,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": 9,
    },
    {
        "name": "hydraneon",
        "index": 9,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "animative_type": "g",
        "evolves_to": None,
    },
]